const express = require('express');
const morgan = require('morgan'); 
const app = express();
app.listen(3000,(err)=>{
    if(err){
        console.log('err : ',err);
    }
    console.log('server is up');
});
app.all('/',(req,res)=>{
        res.status(200).send("welcme to home");
});

/*node module
express : framework 
npm install express --save

middleware : 
1) morgan : print out log information
2) body parse : parse body in req and extract info


semantic versioning
majorChanges.minorVersion.patch
major : major breaking changes
minor chanes: some minor changes
patch : bug fixes
explicitily specift pkg version : npm install express@4.0.0
patch acceptable : npm install express@"~4.0.0"
minor changes : npm install express@"^4.0.0"
dependancies : whene we specify on which thire party module out program is depend upon or we are using

package-lock.json : automaticly generated by npm
store exact tree that was gererated when you install othernode module 
*/